# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 140a9d65acd6ab2ea1993c546bd74a10608646fc227198b16e7d10c2c9e18406e5decae0ad97efad5f7d2e0693056380735d04259f91cd326b6876c462641ec4

test:
  secret_key_base: e5cfdc4205a66e44bd4ead7f84adbddacd4b70441b116f844524bcb483525db582a061baa5cf740049711e56a6ae0b306fdfb46be6dbc658aacfe311ea2b94a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
